version: 2

project_name: porthog

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/porthog
    binary: porthog
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - repository:
      owner: z1j1e
      name: homebrew-porthog
    homepage: "https://github.com/z1j1e/porthog"
    description: "Cross-platform port management CLI — find what's hogging your ports"
    license: "MIT"
    install: |
      bin.install "porthog"
    test: |
      system "#{bin}/porthog", "version"
